### ISSUE TITLE
QGIS has "Union (multiple)" tool natively

### ISSUE THREAD

**Issue by DelazJ** [Almeida100/Multi-Union#2]
Hi @Almeida100 
The plugin description states
> This plugin performs a similar operation to the UNION tool available in the Vector -> Geoprocessing Tools menu of QGis3, but in **this tool it is only possible to use two layers at a time**,

While this appears true for that specific tool, QGIS provides the [Union (multiple)](https://docs.qgis.org/3.28/en/docs/user_manual/processing_algs/qgis/vectoroverlay.html#union-multiple) tool that afaik does not have a limit of layers to run and does the same think as Union.
Just wanted to share that in the case you didn't know, so that so you could correct the comparison and do not misguide people about what QGIS can't natively do.
Regards,
DelazJ

**Comment by Almeida100** [comment]
Hi DelazJ
Many thanks for you remarks.
In fact, the native tool is giving some bad reports (https://gis.stackexchange.com/questions/464634/qgis-multiple-union-fails).
This plugin was designed to avoid problems like those mentioned in the link above, as far as possible.
This plugin also allows you to select the fields of the input layers that will be part of the result.
Version 3.28.12-Firenze LTR does not have any tool in its Menus/Submenus that performs the "Multiple Union" function.
Best Regards

**Comment by DelazJ** [comment]
@Almeida100  Don't get me wrong, please. I dont say that your plugin is useless. It might have its use case and being able to select the field you want to keep from other layers is a great one.
My point is just that QGIS can union natively more than three layers at the same time (unlike what may be implied by the description I quoted earlier). It is not called "Union" but "Union (multiple)" [introduced in 3.26](https://qgis.org/en/site/forusers/visualchangelog326/index.html#feature-overlay-tools-with-multiple-overlay-layers-support) and yes, it is not in vector submenu but sooo many algs are not in the shortcuts menu. They are in processing toolbox.
My concern is about the description, not the plugin itself.
Kind regards.
